### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by redjax**
Add typing_extensions dependency to pyproject.toml.

Per this issue: https://github.com/karpetrosyan/hishel/issues/160#issuecomment-1884900131

### CODE REVIEW

**Comment by karpetrosyan** [comment]
Thanks for this pull request :pray:
You have added it as an optional dependency, like `pip install hishel[sqlite]`
Instead, It should be alongside httpx

https://github.com/karpetrosyan/hishel/blob/6742e73b59c9fa0699080b5f730c0e4e298a8655/pyproject.toml#L32

We also need to remove it from requirements.txt and add a changelog entry.

**Comment by redjax** [comment]
I was trying to be respectful of the nice, clean dependency list you have, but I realize adding it as an optional dependency wouldn't have helped! Thanks for the correction

**Comment by redjax** [comment]
Removed `typing_extensions` from `requirements.txt` (missed that part in your reply to my issue). As for updating the changelog, is this done automatically, or is that a manual change?

**Comment by karpetrosyan** [comment]
>  or is that a manual change?

I't a manual change. I will help you.

**Comment by karpetrosyan** [comment]
Thank you for your contribution :tada:

**Review by karpetrosyan — APPROVED** [review]

**Pull request merged**
