### PR TITLE
Add client tests

### PR DESCRIPTION
**Pull request by umnovI**
Adding tests for:
- [x] GET caching
- [x] POST caching
- [x] HEAD no caching
- [x] `force_cache` extension
- [x] `cache_disabled` extension

Any other methods should be tested?

### CODE REVIEW

**Review by karpetrosyan — APPROVED** [review]

**Comment by umnovI** [comment]
Got rid of multiple function calls for date formatting in tests. Made it a single call and just used a var everywhere else.

**Comment by karpetrosyan** [comment]
You have merge access, right?

**Comment by umnovI** [comment]
> You have merge access, right?

I do. I wasn't sure if you want me to do it or not tho.

**Comment by karpetrosyan** [comment]
Feel free to merge the RP that you think is ready.

**Comment by umnovI** [comment]
> Feel free to merge the RP that you think is ready.

Ok! Tbh I thought if this is enough tests and maybe we should add tests for every method?

**Comment by karpetrosyan** [comment]
I think these tests are more than enough. Clients are not really important because all the caching logic is defined in the transports.

**Comment by umnovI** [comment]
Ok then.

**Pull request merged**
