### PR TITLE
Add .gitignore to cache directory

### LINKED ISSUE #195: Add a .gitignore file when creating a cache dir
Similar to #194, adding a `.gitignore` file with content `*` into a cache dir would prevent accidental commits.

A real-life example of this is https://github.com/mesonbuild/meson/commit/7437d9862a16bab3fd0c025769d5928f2ed1548e

### PR DESCRIPTION
**Pull request by umnovI**
Closes #195

### CODE REVIEW

**Comment by karpetrosyan** [comment]
Great, Thanks!

**Comment by umnovI** [comment]
Renamed variable for consistency.

**Review by karpetrosyan — APPROVED** [review]

**Comment by umnovI** [comment]
Should it be added to changelog?

**Comment by karpetrosyan** [comment]
yes, let's add a changelog

**Comment by umnovI** [comment]
@karpetrosyan, how does it look?

**Comment by karpetrosyan** [comment]
> @karpetrosyan, how does it look?

lgtm 🎉

**Pull request merged**
